"""
Use coefficients file generated by detide_mod_fields.py and compute tides and surge.

from o.dict

Nomvar              : ETAS IP1(old=1200; new=66060288; level=0,kind=3)
Short Description   : Storm surge
Long  Description   : The storm surge is primarily the combination of the inverse barometer effect (driven by variations in air pressure) and the wind driven isostatic adjustment. Obtained by adjusting storm surge height from the model or by applying harmonic analysis on SSH.
Origin              : Oceanography
State               : Current
Date of state       : 2015-05-19
Optimal compaction  : -
Representation      : Real Variable
Units               : m
Range               : [0 

--------------------------------------------------------------------------------
Nomvar              : SSHT
Short Description   : Tidal sea surface height
Long  Description   : The isolated contribution of tides to the sea surface height (e.g. relative to a geoid).
Origin              : Oceanography
State               : Current
Date of state       : 2019-03-01
Optimal compaction  : -
Representation      : Real Variable
Units               : m
Range               : [-10 10]

"""

import os
# Must be set BEFORE importing numpy, scipy, or utide
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"


from pathlib import Path
import time
import argparse
import numpy as np
import pyarrow.parquet as pq
import pyarrow
import pyarrow.dataset as pads
import multiprocessing
import functools as ft
import itertools as itt
import pandas as pd

from dask import array as da

from tqdm import tqdm
import utide

import cmcio

GLOBAL_BUNCHES_COL = pyarrow.StructArray.from_arrays([], fields=[])
EXEC_START_TIME = time.perf_counter()

def read_cmd_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="detide model outputs on grids (compute tide and surge components)")
    
    parser.add_argument("--inp_dir", required=True, type=Path,
                        help="path to the input directory, files containing SSH")

    parser.add_argument("--inp_file_suffix", required=False, default="", type=str,
                            help="file name suffix, for file selection, i.e. _000 for control member")



    # total water level field name
    parser.add_argument("--twl_nomvar", required=False, default="SSH", type=str,
                        help="total water level field name")


    parser.add_argument("--tide_coef_file", required=True, type=Path,
                        help="path to the parquet file containing tide coefficients from utide")


    parser.add_argument("--out_dir", required=True, type=Path,
                        help="path to the output directory")

    parser.add_argument("--offset_hours", required=False, type=int, default=6 * 24,
                            help="disregard first offset_hours from file (i.e. 6 days of spinup for GESPS)")
    
    # total water level field name
    parser.add_argument("--out_filetype", required=False, default="fst", choices=["fst", "nc"],
                        help="Type of the ouptut files")


    parser.add_argument("--walltime_minutes", required=False, default=150,
                        help="Maximum time the script is allowed to run")

    parser.add_argument("--atomic_work_minutes", required=False, default=30,
                        help="minutes required to execute a meaningful chunk of work")

    
    return parser.parse_args()


def read_coef_table(pth: Path) -> pyarrow.Table:
    """
    columns: i, j, bunch
    bunch - computed by utide
    """
    tb = pq.read_table(pth, memory_map=True)
    i_arr, j_arr = tb.column("i").to_numpy(), tb.column("j").to_numpy()
    bunch_arr = tb.column("bunch")
    return i_arr, j_arr, bunch_arr

def read_coef_spatial_indices(pth: Path) -> pyarrow.Table:
    """
    columns: i, j
    """
    tb = pq.read_table(pth, columns=["i", "j"])
    i_arr, j_arr = tb.column("i").to_numpy(), tb.column("j").to_numpy()
    return i_arr, j_arr



def read_coef_table_meta(pth: Path) -> pq.FileMetaData:
    return pq.read_metadata(pth)


def reconstruct(t, r):
    """
    Args:
        r (tuple): (i_beg, i_end), i_end - end index of a slice non-inclusive
    """
    global GLOBAL_BUNCHES_COL

    bunch_inp = GLOBAL_BUNCHES_COL.slice(r[0], r[1] - r[0]).to_numpy(zero_copy_only=False)
    res = []
    for b in bunch_inp:
        bunch_out = utide.reconstruct(t, b, verbose=False)
        res.append(bunch_out.h)
    return res


def compute_tide_surge(f_inp: Path,
                       coef_i: np.ndarray, 
                       coef_j: np.ndarray,
                       args: argparse.Namespace):
    """
    computes tide and surge fields and save in the same layout 
    as input file but to the output directory
    """
    global GLOBAL_BUNCHES_COL
    
    tide_nomvar = "SSHT"
    etas_nomvar = "ETAS"

    out_dir: Path = args.out_dir
    

    ds_in = cmcio.open_fst(f_inp)[0]

    # drop first offset hours
    dt_offest = pd.Timedelta(hours=args.offset_hours)
    ds_in = ds_in.where(ds_in.time >= (ds_in.time[0] + dt_offest), drop=True)

    t = ds_in.time.values

    ssh = ds_in[args.twl_nomvar]
    ssh = ssh.squeeze()
    

    print(f"Loaded {args.twl_nomvar} into memory.")

    
    print("computing tides")
    total_items = len(GLOBAL_BUNCHES_COL)
    num_workers = 250
    step = total_items // num_workers
    ranges = [(i, min(i + step, total_items)) for i in range(0, total_items, step)]
    
    print(f"Distributing {total_items} items across {num_workers} workers via index ranges...")
    reconstruct_inj = ft.partial(reconstruct, t)

    
    with multiprocessing.Pool(processes=num_workers) as pool:
        results = list(tqdm(
            itt.chain.from_iterable(
                pool.map(reconstruct_inj, ranges)
            ), total=total_items, desc="Reconstructing tides"
        ))

    
    tide_data = np.zeros(ssh.shape)
    tide_data[:, coef_i, coef_j] = np.array(results).T
    tide = ssh.copy(data=tide_data).where(~ssh.isnull())
    

    for attn, attv in tide.attrs.items():
        if isinstance(attv, bool):
            tide.attrs[attn] = str(attv)

    ds_in[tide_nomvar] = tide
    ds_in[etas_nomvar] = ssh - tide


    print(f"Saving tides and surge ")
    output_vars = [tide_nomvar, etas_nomvar]
    if args.out_filetype in ["cdf", "nc"]:

        f_out: Path = out_dir / f"{f_inp.name}.{args.out_filetype}"
        
        trouble_attrs = [att for att in ds_in.attrs if att.startswith("fst_")]
        for att in trouble_attrs:
            ds_in.attrs.pop(att, None)

        for v in output_vars:
            trouble_attrs = [att for att in ds_in[v].attrs if att.startswith("fst_")]
            for att in  trouble_attrs:
                ds_in[v].attrs.pop(att, None)

        # Create a dictionary specifying compression settings for each variable
        # 'complevel' ranges from 1 (fastest/least) to 9 (slowest/most). 4 or 5 is the sweet spot.
        comp = dict(zlib=True, complevel=5)

        # Apply this setting to all data variables in your Dataset
        encoding = {var: comp for var in output_vars}

        ds_in[output_vars].to_netcdf(f_out, encoding=encoding)
    else:
        for v in output_vars:
            v_f_out = out_dir / v / f_inp.name
            v_f_out.parent.mkdir(exist_ok=True)

            nrecords = cmcio.write_fst(
                ds_in[[v,]], v_f_out, 
                storage="xdf",
                overwrite=True
            )



def claim_file(lock_file_path):
    """
    Attempts to atomically claim a file by creating a unique .lock file.
    Returns True if successfully claimed, False if another job beat us to it.
    """
    try:
        # Atomic file creation across cluster network nodes
        fd = os.open(lock_file_path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        with os.fdopen(fd, 'w') as f:
            f.write(f"Claimed by PBS_JOBID: {os.environ.get('PBS_JOBID', 'local')}\n")
        return True
    except FileExistsError:
        return False


def get_remaining_minutes(args):
    ellapseed_minutes = (time.perf_counter() - EXEC_START_TIME) // 60
    return args.walltime_minutes - ellapseed_minutes


def work(args):
    global GLOBAL_BUNCHES_COL
    assert isinstance(args.inp_dir, Path)

    i_arr, j_arr, GLOBAL_BUNCHES_COL = read_coef_table(args.tide_coef_file)

    inp_files = [f for f in args.inp_dir.iterdir() if f.is_file() and f.name.endswith(args.inp_file_suffix)]

    out_dir: Path = args.out_dir

    for i, f in enumerate(inp_files):

        f_lock = out_dir / f"{f.name}.lock"
        f_done = out_dir / f"{f.name}.done"

        if f_done.exists():
            print(f"Nothing to do for {f}, marked as done with {f_done}")
            continue

        if f_lock.exists():
            print(f"Looks like {f} is being worked on, as {f_lock} exists, skipping")
            continue

        remaining_minutes = get_remaining_minutes(args)
        if remaining_minutes < args.atomic_work_minutes:
            print(f"Won't be able to do much work in {remaining_minutes}, exiting")
            return

        
        if claim_file(f_lock):
            try:
                print(f"Processing {f} ({i = })")
                compute_tide_surge(f, i_arr, j_arr, args)
                claim_file(f_done) # create done file
            finally:
                f_lock.unlink()
    
    print("All files processed")

def main():
    args = read_cmd_args()
    work(args)


def test():
    inp_dir = Path("/home/sssm001/data/ppp7/u2/maestro/gesps_v001_final_cycles_V2/gridpt/gesps.f.output_pre-level/")
    args = argparse.Namespace(
        **dict(
            inp_dir=inp_dir,
            inp_file_suffix="360_000",
            out_dir=Path("test_data/gesps-detide-fields-test/gesps_v001_final_cycles_V2"),
            twl_nomvar="SSH",
            tide_coef_file=Path("test_data/gesps-detide-fields-test/utide-coefs_chunking_x_10_y_10_2021101800_2022060100_12h.parquet"),
            out_filetype="fst",
            walltime_minutes=150,
            offset_hours=6 * 24 - 1,
            atomic_work_minutes=30 # do one file in 30 minuts, for sure
        )
    )

    work(args)


if __name__ == "__main__":
    run_test = True
    if run_test:
        test()
    else:
        main()
