"""
Use coefficients file generated by detide_mod_fields.py and compute tides and surge.

from o.dict

Nomvar              : ETAS IP1(old=1200; new=66060288; level=0,kind=3)
Short Description   : Storm surge
Long  Description   : The storm surge is primarily the combination of the inverse barometer effect (driven by variations in air pressure) and the wind driven isostatic adjustment. Obtained by adjusting storm surge height from the model or by applying harmonic analysis on SSH.
Origin              : Oceanography
State               : Current
Date of state       : 2015-05-19
Optimal compaction  : -
Representation      : Real Variable
Units               : m
Range               : [0 

--------------------------------------------------------------------------------
Nomvar              : SSHT
Short Description   : Tidal sea surface height
Long  Description   : The isolated contribution of tides to the sea surface height (e.g. relative to a geoid).
Origin              : Oceanography
State               : Current
Date of state       : 2019-03-01
Optimal compaction  : -
Representation      : Real Variable
Units               : m
Range               : [-10 10]

"""

def setup_worker_env():
    import os
    # Must be set BEFORE importing numpy, scipy, or utide
    os.environ["MKL_NUM_THREADS"] = "1"
    os.environ["NUMEXPR_NUM_THREADS"] = "1"
    os.environ["OMP_NUM_THREADS"] = "1"
    os.environ["OPENBLAS_NUM_THREADS"] = "1"

setup_worker_env()

import os
from pathlib import Path
import time
import argparse
import numpy as np
import pyarrow.parquet as pq
import pyarrow
import pyarrow.dataset as pads
import multiprocessing
import functools as ft
import itertools as itt
import pandas as pd
import xarray
import fasteners

from dask import array as da
from dask.delayed import delayed
from dask.diagnostics import ProgressBar

import dask.dataframe as dd


from distributed import Client, wait
from dask_jobqueue.pbs import PBSCluster
import duckdb

import utide
import cmcio

EXEC_START_TIME = time.perf_counter()

import dask
from distributed import WorkerPlugin


# 2. REDIRECT THE SPILLER (Breaks the /dev/shm RAM-disk loop)
# Point this to your HPC's true physical scratch space (usually /tmp or /scratch)
dask.config.set({'temporary-directory': os.environ.get("TMPDIR", os.getcwd())})

class ThreadLimitPlugin(WorkerPlugin):
    def setup(self, worker):
        setup_worker_env()




def read_cmd_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="detide model outputs on grids (compute tide and surge components)")
    
    parser.add_argument("--inp_dir", required=True, type=Path,
                        help="path to the input directory, files containing SSH")

    parser.add_argument("--inp_filetype", required=False, default="fst", type=str,
                            help="type of the input files", choices=["fst, nc"])
    

    parser.add_argument("--inp_file_suffix", required=False, default="", type=str,
                            help="file name suffix, for file selection, i.e. _000 for control member")



    # total water level field name
    parser.add_argument("--twl_nomvar", required=False, default="SSH", type=str,
                        help="total water level field name")


    parser.add_argument("--tide_coef_file", required=True, type=Path,
                        help="path to the parquet file containing tide coefficients from utide")


    parser.add_argument("--out_dir", required=True, type=Path,
                        help="path to the output directory")

    parser.add_argument("--offset_hours", required=False, type=int, default=6 * 24,
                            help="disregard first offset_hours from file (i.e. 6 days of spinup for GESPS)")
    
    # total water level field name
    parser.add_argument("--out_filetype", required=False, default="fst", choices=["fst", "nc"],
                        help="Type of the ouptut files")


    parser.add_argument("--walltime_minutes", required=False, default=150,
                        help="Maximum time the script is allowed to run")

    parser.add_argument("--atomic_work_minutes", required=False, default=30,
                        help="minutes required to execute a meaningful chunk of work")

    
    return parser.parse_args()


def read_coef_table(pth: Path) -> pyarrow.Table:
    """
    columns: i, j, bunch
    bunch - computed by utide
    """
    tb = pq.read_table(pth, memory_map=True)
    i_arr, j_arr = tb.column("i").to_numpy(), tb.column("j").to_numpy()
    bunch_arr = tb.column("bunch")
    return i_arr, j_arr, bunch_arr

def read_coef_spatial_indices(pth: Path):
    """
    columns: i, j
    """
    tb = pq.read_table(pth, columns=["i", "j"])
    i_arr, j_arr = tb.column("i").to_numpy(), tb.column("j").to_numpy()
    return i_arr, j_arr



def read_coef_table_meta(pth: Path) -> pq.FileMetaData:
    return pq.read_metadata(pth)



def reconstruct(tide_coef_pth: Path, r, t_beg, t_end, freq):
    """
    Args:
        t_beg, t_end: inclusive time period limits
        freq: time step required
        tide_coef_file: path to the parquet file with tide coefficients
        r (tuple): (i_beg, i_end) - spatial chunk, i_beg - start index of a slice, i_end - end index of a slice non-inclusive
    """
    
    # bunch_inp = GLOBAL_BUNCHES_COL.slice(r[0], r[1] - r[0]).to_numpy(zero_copy_only=False)

    offset = r[0]
    limit = r[1] - r[0]
    column_name = "bunch"
    with duckdb.connect() as con:
        query = f"""
            select {column_name} from read_parquet('{tide_coef_pth}') 
            LIMIT {limit} OFFSET {offset}
        """
        tb = con.sql(query).fetch_arrow_table()

    bunch_inp = tb[column_name].to_numpy(zero_copy_only=False)
    t = pd.date_range(t_beg, t_end, freq=freq, inclusive="both")

    return [
        utide.reconstruct(t, b, verbose=False).h for b in bunch_inp
    ]



def compute_tide_surge(f_inp: Path,
                       coef_i: np.ndarray, 
                       coef_j: np.ndarray,
                       client,
                       args: argparse.Namespace):
    """
    computes tide and surge fields and save in the same layout 
    as input file but to the output directory
    """
    
    
    tide_nomvar = "SSHT"
    etas_nomvar = "ETAS"

    out_dir: Path = args.out_dir
    
    if args.inp_filetype == "nc":
        ds_in = xarray.open_dataset(f_inp)
        if "time_counter" in ds_in.dims:
            ds_in = ds_in.rename({"time_counter": "time"})

        ds_in = ds_in.chunk({dn: 100 for dn in ds_in.dims})
    else:
        ds_in = cmcio.open_fst(f_inp)[0]

    # drop first offset hours
    dt_offest = pd.Timedelta(hours=args.offset_hours)
    ds_in = ds_in.where(ds_in.time >= (ds_in.time[0] + dt_offest), drop=True)

    t = ds_in.time.values
    freq = pd.to_timedelta(t[1] - t[0])
    n_times = len(t)

    ssh = ds_in[args.twl_nomvar]
    ssh = ssh.squeeze()

    n_points = len(coef_i)    
    batch_size = 500
    batch_beg_indices = np.arange(n_points, step=batch_size, dtype=int)
    batch_end_indices = batch_beg_indices + batch_size

    if batch_end_indices[-1] > n_points:
        batch_end_indices[-1] = n_points

    batch_ranges = list(zip(batch_beg_indices, batch_end_indices))




    lazy_reconstruct = delayed(reconstruct)
    # 2. Build a list of lazy pointers. This is INSTANT and does not block.
    lazy_chunks = [
        lazy_reconstruct(args.tide_coef_file, r, t[0], t[-1], freq) 
        for r in batch_ranges
    ]

    
    persisted_collection = client.compute(lazy_chunks)

    def stream_chunks(futures):
        for f in futures:
            data = client.gather(f)
            yield data
            del data  # Explicitly clear client-side intermediate reference
    
    local_data_stream = stream_chunks(persisted_collection)

    tide_zip = np.array(
        list(itt.chain.from_iterable(local_data_stream)), 
        dtype=np.float32).T

    tide_full = np.zeros(ssh.shape, dtype=np.float32)
    tide_full[:, coef_i, coef_j] = tide_zip

    new_chunking = {dn: -1  for dn in ssh.dims}
    
    # Get the total number of registered workers
    num_workers = len(client.scheduler_info()['workers'])
    
    new_chunking["time"] = max(int(ssh.sizes["time"] // num_workers), 1)

    ssh = ssh.chunk(new_chunking)

    # read ssh into memory
    # 1. Break the open dask-backed array into individual lazy chunks
    chunks = ssh.data.to_delayed().flatten()

    # 3. Reconstruct the clean, unified NumPy array locally on the client
    ssh_numpy = np.concatenate(dask.compute(*chunks)).reshape(ssh.shape)
    
    tide = ssh.copy(data=np.where(~np.isnan(ssh_numpy), tide_full, np.nan))

    for attn, attv in tide.attrs.items():
        if isinstance(attv, bool):
            tide.attrs[attn] = str(attv)

    ds_in[tide_nomvar] = tide
    ds_in[etas_nomvar] = tide.copy(data=ssh_numpy - tide_full)


    print(f"Saving tides and surge ")
    output_vars = [tide_nomvar, etas_nomvar]

    # zarr_pth = args.out_dir / f"{f_inp.name}.zarr"
    # ds_out = ds_in[output_vars]
    # target_chunks = {dn: ssh.data.chunks[di] for di, dn in enumerate(ssh.dims)}
    # lazy_zarr = ds_out.chunk(target_chunks).to_zarr(zarr_pth, 
    #                                        compute=False, 
    #                                        mode="w")

    # Wrap your Zarr computation statement with the progress bar context
    # with ProgressBar():
    #     lazy_zarr.compute()


    if args.out_filetype in ["cdf", "nc"]:

        fname = f"{f_inp.name}".lower().replace("ssh", "etas_ssht")
        if not fname.endswith(f".nc"):
            fname = f"{fname}.nc"

        f_out: Path = out_dir / f"{fname}"
        # Create a dictionary specifying compression settings for each variable
        # 'complevel' ranges from 1 (fastest/least) to 9 (slowest/most). 4 or 5 is the sweet spot.
        target_chunksizes = tuple(c[0] for c in ssh.chunks)
        comp = dict(zlib=False, complevel=1, chunksizes=target_chunksizes)
        
        # Apply this setting to all data variables in your Dataset
        encoding = {var: comp for var in output_vars}

        
        print(f"Saving tides and surge to {f_out} with encoding {encoding}")
        ds_in[output_vars].to_netcdf(f_out, encoding=encoding, 
                                            engine="netcdf4", 
                                            format="NETCDF4")

        print(f"Saved tides and surge to {f_out} in netcdf format")
        
    elif args.out_filetype == "fst":
        for v in output_vars:
            v_f_out = out_dir / v / f_inp.name
            v_f_out.parent.mkdir(exist_ok=True)

            print(f"Saving {v} to {v_f_out} in fst format")
            nrecords = cmcio.write_fst(
                ds_in[[v,]], v_f_out, 
                storage="xdf",
                overwrite=True
            )
            print(f"Saved {nrecords} records of {v} to {v_f_out} in fst format")
    else:
        print("No file conversion requested, leaving as zarr")



def get_remaining_minutes(args):
    ellapseed_minutes = (time.perf_counter() - EXEC_START_TIME) // 60
    return args.walltime_minutes - ellapseed_minutes



def get_client(args=None):
    if args is None:
        nnodes = 5
        total_cpu_per_node = 256
        threads_per_worker = 1
        total_memory = "700GB"
    else:
        nnodes = args.nnodes
        total_cpu_per_node = args.total_cpu_per_node
        threads_per_worker = args.threads_per_worker
        total_memory = args.total_memory
    
    cluster = PBSCluster(
        cores=total_cpu_per_node,                     # Total CPU requested per PBS job
        processes=total_cpu_per_node // threads_per_worker,                # Total processes requested per PBS job
        memory=total_memory,                    # Total RAM requested per PBS job
        resource_spec=f"select=1:ncpus={total_cpu_per_node}:mem={total_memory}", # Matches your system qsub/qstat specs
        walltime="03:00:00",
        queue="development",
        # Worker terminates if scheduler is missing for 60 seconds
        # death_timeout=60,
        dashboard_address=None,  # Optional: specify a dashboard address for monitoring
        log_directory=Path("logs")
    )
    cluster.scale(jobs=nnodes)
    return Client(cluster)


def work(args, client: Client | None = None):
    assert isinstance(args.inp_dir, Path)
    assert isinstance(args.tide_coef_file, Path)

    # convert to absolute path for workers    
    args.tide_coef_file = args.tide_coef_file.absolute()

    i_arr, j_arr = read_coef_spatial_indices(args.tide_coef_file)

    
    inp_files = [f for f in args.inp_dir.iterdir() if f.is_file() and f.name.endswith(args.inp_file_suffix)]

    out_dir: Path = args.out_dir

    cleanup_jobs = False
    if client is None:
        client = get_client(args)
        cleanup_jobs = True

    print(f"{client.dashboard_link = }")

    # Register the plugin to bind it globally to all existing and future workers
    client.register_plugin(ThreadLimitPlugin())

    
    for i, f in enumerate(inp_files):

        f_lock = out_dir / f"{f.name}.lock"
        f_done = out_dir / f"{f.name}.done"

        lock = fasteners.InterProcessLock(f_lock)

        if f_done.exists():
            print(f"Nothing to do for {f}, marked as done with {f_done}")
            continue

        remaining_minutes = get_remaining_minutes(args)
        if remaining_minutes < args.atomic_work_minutes:
            raise RuntimeError(f"Won't be able to do much work in {remaining_minutes}, exiting")
            

        acquired = lock.acquire(blocking=False)
        if acquired:
            try:
                print(f"Processing {f} ({i = })")
                compute_tide_surge(f, i_arr, j_arr, client, args)

                client.restart()  # Restart the client to free up memory after each file
                f_done.touch() # create done file
            finally:
                lock.release()
        else:
            print(f"Looks like {f} is being worked on, as {f_lock} exists, skipping")

    
    # if created a cluster, shut it down after processing all files
    if cleanup_jobs:
        client.shutdown()
        client.close()
        if client.cluster is not None:
            client.cluster.close()

    print("All files processed")

def main():
    args = read_cmd_args()
    work(args)


def test():
    inp_dir = Path("/home/sssm001/data/ppp7/u2/maestro/gesps_v001_final_cycles_V2/gridpt/gesps.f.output_pre-level/")
    args = argparse.Namespace(
        **dict(
            inp_dir=inp_dir,
            inp_filetype="fst",
            inp_file_suffix="360_000",
            out_dir=Path("test_data/gesps-detide-fields-test/gesps_v001_final_cycles_V2"),
            twl_nomvar="SSH",
            tide_coef_file=Path("test_data/gesps-detide-fields-test/utide-coefs_chunking_x_10_y_10_2021101800_2022060100_12h.parquet"),
            out_filetype="fst",
            walltime_minutes=150,
            offset_hours=6 * 24 - 1,
            atomic_work_minutes=30 # do one file in 30 minuts, for sure
        )
    )

    work(args)


if __name__ == "__main__":
    run_test = True
    if run_test:
        test()
    else:
        main()
